### ISSUE TITLE
explaining "environment changes" in build parameters

### ISSUE THREAD

**Issue by ktdreyer** [containerbuildsystem/osbs-docs#108]
build_parameters.rst says:

"These may change over time as the environment changes."

What does that mean exactly? Can we give an example of what we're talking about? It's confusing to me to read that "these things change", like who is changing them and why?

**Comment by athos-ribeiro** [comment]
I believe the sentence refers to possible changes in service configurations, like having the koji root url changed. I understand this may be valid to any configuration and I wouldn't oppose to just removing the sentence.

**Comment by ktdreyer** [comment]
Thank you! I've removed the sentence in https://github.com/containerbuildsystem/osbs-docs/pull/111

**Comment by athos-ribeiro** [comment]
Closed through #111
