### ISSUE TITLE
what is "the downward API"

### ISSUE THREAD

**Issue by ktdreyer** [containerbuildsystem/osbs-docs#109]
build_parameters.rst refers to "the downward API". What is that? Is it an OpenShift thing? Can we link to that term or explain that "for dummies"? :)

**Comment by twaugh** [comment]
It's this: https://docs.openshift.com/container-platform/3.11/dev_guide/downward_api.html

**Comment by ktdreyer** [comment]
Thank you! I've added the link at https://github.com/containerbuildsystem/osbs-docs/pull/110

**Comment by athos-ribeiro** [comment]
Can we close this one now #110 is merged?
