### ISSUE TITLE
"Override Parent Image" does not describe multi-stage builds

### ISSUE THREAD

**Issue by ktdreyer** [containerbuildsystem/osbs-docs#118]
This section describes how we can dynamically override the parent image:

https://osbs.readthedocs.io/en/latest/users.html#override-parent-image

It does not mention how this interacts with multi-stage builds. In particular, I want to update the *final* image's `FROM` line, but not the earlier builder `FROM` lines, and the docs clearly tell me OSBS's behavior here.

**Comment by ktdreyer** [comment]
(cc'ing @b-ranto since we were looking at this recently)

**Comment by rcerven** [comment]
it updates just the final parent image
