### ISSUE TITLE
isolated builds and "primary tag"

### ISSUE THREAD

**Issue by ktdreyer** [containerbuildsystem/osbs-docs#94]
The user documentation says:

> Isolated builds will only update the `{version}-{release}` unique tag and the primary tag in target container registry.

What is "the primary tag"?

I promise to write a pull request to make this documentation clearer :)

**Comment by athos-ribeiro** [comment]
Hi Ken,

Thanks for spotting this. We recently updated the tags documentation, but it seems we forgot about this one.

We divide OSBS tags in three categories:

- unique: a tag including the timestamp of when the image was built
- primary: the version-release tag for the image
- floating tags: 'latest', 'version' and any other tag included through configuration (either container.yaml or additional-tags file)

An isolated build will only apply the unique and the primary tags to the image being built.

**Comment by ktdreyer** [comment]
Thank you! It's really clear when you break down those three categories.

Here are my suggested changes for incorporating this: https://github.com/containerbuildsystem/osbs-docs/pull/99

**Comment by twaugh** [comment]
Fixed via #99.
